### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by FarshidRoohi** [ZarinPal/iOS-SDK#3]
- [x] Add Coupon
- [x] #2
- [x] Check Button title alignment in small devices
- [x] Test MPG
- [x] Improve Dark mode
- [x] Purchase type(all, shetab)
- [x] Change didReceive params to dictionary and raw value
- [x] Publish new version :tada:
